"""FMU co-simulation bus stub — equipment-level dynamic simulation.

Real implementation:
    - FMUs are generated by OpenModelica (Modelica language) or PharmaPy's
      process models, exported as FMI 2.0 / FMI 3.0 co-simulation FMUs.
    - The bus runs on Runpod via PyFMU or Assimulo, stepping each registered
      FMU by dt_s at each call.
    - Eclipse Ditto feeds real PAT sensor readings into each FMU's input port
      on every step, closing the virtual-plant feedback loop.

Stub implementation:
    - Toy linear dynamics: output_var = gain * input_var + decay * state_var
    - Deterministic: same inputs and dt produce same outputs.
    - No COPASI, no Tellurium — those are L5 (PKPD/QSP biochemical networks).

CORRECTION (Brief #2): COPASI/Tellurium belong to L5 (PKPD/QSP). L4 uses
equipment-level dynamic simulation (OpenModelica, PharmaPy, OpenFOAM).
"""

from __future__ import annotations

from typing import Final

from zer0pa_biomolecular_explorer.contracts.l4 import L4FMUUnitState


# Gain and decay constants for toy linear dynamics.
# All values intentionally < 1 to ensure stability.
_GAIN: Final[float] = 0.95
_DECAY: Final[float] = 0.05


class _FMUEntry:
    """Internal bookkeeping for a single registered FMU."""

    __slots__ = ("name", "kind", "state_var", "sim_time_s", "last_inputs", "last_outputs")

    def __init__(self, name: str, kind: str, default_state: dict[str, float]) -> None:
        self.name = name
        self.kind = kind
        # Use the mean of default_state values as the single aggregated state scalar.
        if default_state:
            self.state_var: float = sum(default_state.values()) / len(default_state)
        else:
            self.state_var = 0.0
        self.sim_time_s: float = 0.0
        self.last_inputs: dict[str, float] = {}
        self.last_outputs: dict[str, float] = {}


class FMUStubBus:
    """Stub FMI 2.0/3.0 co-simulation bus.

    Real FMUs come from OpenModelica / PharmaPy / PyFMU; this bus is an
    FMI 2.0/3.0 co-simulation bus that would run on Runpod GPU containers.
    Eclipse Ditto injects PAT sensor readings into FMU inputs on each step.

    Toy dynamics (deterministic, stable):
        output_k = GAIN * input_k + DECAY * state_var
        state_var_new = GAIN * state_var + DECAY * mean(input_values)

    This ensures same inputs produce same outputs (reproducible) and the
    system is asymptotically stable (bounded outputs, no divergence).
    """

    def __init__(self, bus_format: str = "FMI_2_0") -> None:
        self.bus_format = bus_format
        self._fmus: dict[str, _FMUEntry] = {}

    def register_fmu(
        self,
        name: str,
        kind: str,
        default_state: dict[str, float],
    ) -> None:
        """Register a named FMU with an initial state dict.

        In real usage, this would load the FMU binary from an artefact store
        (S3 bucket or Runpod volume) and initialise it per FMI 2.0 §4.2.4.
        """
        self._fmus[name] = _FMUEntry(name=name, kind=kind, default_state=default_state)

    def step(
        self,
        name: str,
        dt_s: float,
        inputs: dict[str, float],
    ) -> L4FMUUnitState:
        """Advance the named FMU by dt_s seconds.

        Toy dynamics:
            For each input key k:
                output[k] = GAIN * inputs[k] + DECAY * state_var

            state_var_new = GAIN * state_var + DECAY * mean(input_values or 0)

        Returns an L4FMUUnitState snapshot after the step.

        Raises KeyError if the FMU has not been registered.
        """
        entry = self._fmus[name]

        outputs: dict[str, float] = {}
        for k, v in inputs.items():
            outputs[k] = _GAIN * v + _DECAY * entry.state_var

        mean_input = sum(inputs.values()) / len(inputs) if inputs else 0.0
        entry.state_var = _GAIN * entry.state_var + _DECAY * mean_input
        entry.sim_time_s += dt_s
        entry.last_inputs = dict(inputs)
        entry.last_outputs = outputs

        return L4FMUUnitState(
            fmu_name=name,
            unit_op_kind=entry.kind,
            inputs=dict(inputs),
            outputs=outputs,
            state_vars={"state_var": entry.state_var},
            sim_time_s=entry.sim_time_s,
        )

    def snapshot(self) -> list[L4FMUUnitState]:
        """Return the current state snapshot for every registered FMU."""
        result: list[L4FMUUnitState] = []
        for entry in self._fmus.values():
            result.append(
                L4FMUUnitState(
                    fmu_name=entry.name,
                    unit_op_kind=entry.kind,
                    inputs=dict(entry.last_inputs),
                    outputs=dict(entry.last_outputs),
                    state_vars={"state_var": entry.state_var},
                    sim_time_s=entry.sim_time_s,
                )
            )
        return result
